# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48877edc192736da6fa9fcbe26962634440d9cf63bca16bc0632fb0b05ff72237946a3b27afb6c4c6453cd6640096872ea7170ee933119a3c1a4989b3d91127d

test:
  secret_key_base: 14f671bb678190019c552fcec5b9aa69e865e5ee99b883f9805107ab58cc51fe606dab28875cdc530d1e0419f5aec540e5382422357ede33d589e9f234eb2f3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
